apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: '4000'
  DB_CONNECTION_URL: mongodb://backend:swordfish@mongo:27017/backend
  MAIL_SERVICE_BASE_URL: http://mail-service:4100
  VERIFICATION_SERVICE_URL: verification-service:4010
