---
apiVersion: v1
kind: Secret
metadata:
  name: opentelemetry-collector-secret
data:
  OTEL_ENDPOINT_URL: {{ - b64enc .Values.opentelemetry.collector.endpoint }}
  OTEL_AUTH_HEADER: {{ - b64enc .Values.opentelemetry.collector.auth }}
