---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: opentelemetry
  name: opentelemetry-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          # http:
          #   endpoint: 0.0.0.0:4318

    exporters:
      otlphttp:
        endpoint: '${OTEL_ENDPOINT_URL}'
        headers: { 'Authorization': '${OTEL_AUTH_HEADER}' }

      # logging:
      #   loglevel: debug
      #   sampling_initial: 5
      #   sampling_thereafter: 200

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp]
          # exporters: [otlphttp, logging]

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: opentelemetry-collector
  namespace: opentelemetry
  name: opentelemetry-collector
spec:
  selector:
    app: opentelemetry-collector
  ports:
    - name: metrics
      port: 8888
      targetPort: metrics
    - name: grpc
      port: 4317
      targetPort: grpc
    # - name: http
    #   port: 4318
    #   targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opentelemetry-collector
  namespace: opentelemetry
  name: opentelemetry-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetry-collector
  template:
    metadata:
      labels:
        app: opentelemetry-collector
    spec:
      containers:
        - name: opentelemetry-collector
          image: otel/opentelemetry-collector:latest
          resources: {}
          args:
            - --config=/etc/opentelemetry-collector/config.yaml
          envFrom:
            - secretRef:
                name: opentelemetry-collector-secret
          ports:
            - name: metrics
              containerPort: 8888
              protocol: TCP
            - name: grpc
              containerPort: 4317
              protocol: TCP
            # - name: http
            #   containerPort: 4318
            #   protocol: TCP
          volumeMounts:
            - mountPath: /etc/opentelemetry-collector
              name: config
      volumes:
        - name: config
          configMap:
            name: opentelemetry-collector-config
