---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: '4000'
  DB_CONNECTION_URL: mongodb://backend:swordfish@mongo:27017/backend
  MAIL_SERVICE_BASE_URL: http://mail-service:4100
  VERIFICATION_SERVICE_URL: verification-service:4010

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 4000
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: martinnirtl/demos.opentelemetry.backend:latest
          resources: {}
          envFrom:
            - configMapRef:
                name: backend-config
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP

{{- if .Values.ingress.enabled -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: otel-demo
  name: backend-ingress
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: {{ print "Host(`" .Values.ingress.host "`)" }}
      kind: Rule
      services:
        - name: backend
          port: 4000
  tls:
    certResolver: cert-resolver
{{- end }}