apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: template-service
  name: template-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-service
  template:
    metadata:
      labels:
        app: template-service
    spec:
      containers:
        - name: template-service
          image: martinnirtl/demos.opentelemetry.template-service:latest
          resources: {}
          command:
            - node
            - src/start.js
          envFrom:
            - configMapRef:
                name: template-service-config
          ports:
            - containerPort: 4200
