apiVersion: v1
kind: Service
metadata:
  name: mail-service
  labels:
    app: mail-service
spec:
  selector:
    app: mail-service
  ports:
    - name: '4100'
      port: 4100
      targetPort: 4100
