apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel-collector
  name: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - name: '8888'
      port: 8888
      targetPort: 8888
    - name: '4317'
      port: 4317
      targetPort: 4317
    - name: '4318'
      port: 4318
      targetPort: 4318
