apiVersion: v1
kind: Service
metadata:
  labels:
    app: template-service
  name: template-service
spec:
  selector:
    app: template-service
  ports:
    - name: '4200'
      port: 4200
      targetPort: 4200
