apiVersion: v1
kind: Service
metadata:
  labels:
    app: verification-service
  name: verification-service
spec:
  selector:
    app: verification-service
  ports:
    - name: '4010'
      port: 4010
      targetPort: 4010
